services:
  nestjs-app:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - ollama
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_API_URL=http://ollama:11434
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - app-network
    # command: ["pull", "llama3.2"]

  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
        - "80:80"
    networks:
        - app-network
    depends_on:
        - nestjs-app
        - certbot
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama:
    driver: local
  certbot:
    driver: local
