services:
  nestjs-app:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - ollama
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    #   - OLLAMA_API_URL=http://ollama:11434
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - app-network
    # command: ["pull", "llama3.2"]

networks:
  app-network:
    driver: bridge

volumes:
  ollama:
    driver: local
